### ISSUE TITLE
Update the usage of puppet-redirect

### ISSUE THREAD

**Issue by warpech** [StarcounterSamples/Chatter#11]
Switch to be using the new path `/sys/puppet-redirect/puppet-redirect.html`.

Please release a new version when done.

**Comment by warpech** [comment]
Do this after Starcounter 2.2 stable is released, because previous stable (2.1.177) uses a different path.

**Comment by aloscha** [comment]
That path is already on master (also checked in branches, which is waiting to merge). So i think just close the issue.

**Comment by warpech** [comment]
Looking good, thanks.
