### ISSUE TITLE
Simplify Chatter data model

### ISSUE THREAD

**Issue by warpech** [StarcounterSamples/Chatter#9]
Currently, Chatter data model looks like this:

- ChatGroup (aka chat room)
- ChatMessage, which belongs to ChatGroup (there can be 0 or more messages in a ChatGroup)
- ChatAttachment, which belongs to a ChatMessage (there can be 0 or more attachments in a ChatMessage)

This model is inspired by email folders, emails and email attachments. But actually all popular IM's in the world (Skype, WhatsApp, etc), have a simpler model:

- ChatGroup (aka chat room)
- ChatMessage, which belongs to ChatGroup and can be text or media (there can be 0 or more messages in a ChatGroup)

So, in case of Chatter, ChatAttachment should be merged into ChatMessage.

Thanks to that, we will have simpler code and nicer UX.

**Comment by warpech** [comment]
WhatsApp reference image: 

![](https://www.cdn.whatsapp.net/img/v3/en/s3-chataudio.png)

**Comment by aloscha** [comment]
![zdjecie 07 04 2016 17 31 03](https://cloud.githubusercontent.com/assets/5141943/14367021/fe7d5cdc-fd15-11e5-9fd4-78fd1c634200.jpg)
We will change the ralation to ChatRoom --- ChatMessage --- Something
People could send one image or one contact or text via different applications. Each application will place in dropdown with add button. Clicking to that button cause adding "something" to chatter.

**Comment by aloscha** [comment]
Could you @warpech review current version of chatter?
User for that:
- Simplified (branch: Simplify_Chatter_data_model_#9)
- Images (branch: Simplify_Chatter_data_model_#9)
- Chatter (branch: Simplify_Chatter_data_model_#9)

**Comment by warpech** [comment]
### Informative

- [ ] All apps. Code does not follow [the style guide](https://starcounter.gitbooks.io/guidelines/content/coding_style/csharp_code_formatting.html). I didn't send you that link before, so take no offence. Just please conform to it in future.

### Must to be fixed before merge

- [ ] Simplified. Some of the classes in Ring6/Chat have class definitions that are different from the file names (ChatAttachment.cs, ChatDraftAnnouncement.cs)
- [ ] Simplified. `Illustration` now extends from `Relation`. It is not properly used as a relation, because it `WhatIs` is a self-reference (seen in Images MainHandlers.cs). I like this direction, though. Maybe you can set `[SynonymousTo(WhatIs)] Content` and `[SynonymoutsTo(ToWhat)] Concept`?
- [ ] Simplified. `ChatMessageText` should not be a `Relation`, because it is one-to-many
- [ ] Chatter. After I'm signed in (using SignIn) app, my messages are still presented as from "Anonymous"

- [ ] Chatter. By pressing the blue "Save" button in the Image drop area, I am able to commit the transaction. After that, pressing F5 shows the message draft on top of the page:
 - Screen 1:  
<img width="1226" alt="screen shot 2016-05-04 at 15 05 25" src="https://cloud.githubusercontent.com/assets/566463/15015041/cf701bec-1209-11e6-8f91-740f7bb25b12.png">

 - Screen 2:  
<img width="1420" alt="screen shot 2016-05-04 at 15 05 56" src="https://cloud.githubusercontent.com/assets/566463/15015028/c2c216ca-1209-11e6-9f30-e4529a7818cf.png">

### Can be fixed after merge / Promoted to separate issues

- [ ] Images/Chatter. Image drop area is rendered above the "Save" button.
   - Screen:  
<img width="1274" alt="screen shot 2016-05-04 at 14 59 44" src="https://cloud.githubusercontent.com/assets/566463/15014906/f6356fbc-1208-11e6-9232-27104f3e0953.png">

- [ ] Image/Chatter. Cosmetic. The form fields are wider than their containers:
  - Screen:  
<img width="1271" alt="screen shot 2016-05-04 at 15 07 58" src="https://cloud.githubusercontent.com/assets/566463/15015081/17628a02-120a-11e6-9c82-91e343b12bf0.png">
- [ ] Web Socket messages are not pushed to other sessions/windows.
- [ ] Images. In the chat message, the image thumbnail is a link that goes to an empty page. It should go to a page that displays a big image.
   - Screen:  
<img width="98" alt="screen shot 2016-05-04 at 15 01 49" src="https://cloud.githubusercontent.com/assets/566463/15014932/2b53b262-1209-11e6-847a-f07eacab9d8b.png">

**Comment by aloscha** [comment]
> Chatter. By pressing the blue "Save" button in the Image drop area, I am able to commit the transaction. After that, pressing F5 shows the message draft on top of the page:

Waiting for https://github.com/Starcounter/Starcounter/issues/3619

> Image/Chatter. Cosmetic. The form fields are wider than their containers:
It could be styled insine luncher?

> Images. In the chat message, the image thumbnail is a link that goes to an empty page. It should go to a page that displays a big image.
Yeah I add to image issue with that

**Comment by aloscha** [comment]
@warpech I fixed task that is necessary to merge whole solution. I also fix Chatter to be works with new StarCounter nightly version.

**Comment by warpech** [comment]
Merged to master.

I will now create issues for remaining work items.

**Comment by warpech** [comment]
Good job @aloscha, a lot of feedback for future improvements!
